export const diagnosticQuestions = [
  {
    id: 1,
    source: 'File 1',
    concept: 'Exponential growth by repeated multiplication',
    prompt: 'Money in a bank triples every 8 years. If $100 is deposited today, what will its value be after 32 years?',
    choices: [' $8,500', '$8,100', '$1,600', '$400'],
    answer: 'b',
  },
  {
    id: 2,
    source: 'File 1',
    concept: 'Solving a system of linear equations',
    prompt: 'The y-coordinate of the point of intersection of the graph of -x + 4y = -50 and x + y = 20 is:',
    choices: ['6', '0', '-14', '-6'],
    answer: 'd',
  },
  {
    id: 3,
    source: 'File 1',
    concept: 'Surface area of a rectangular prism',
    prompt: 'The rectangular box shown has a square base and a closed top. The height is twice the length of one side of the base. Its surface area in terms of x is:',
    choices: ['20x', '8x + 2x^2', '10x^2', '6x^2'],
    answer: 'c',
  },
  {
    id: 4,
    source: 'File 1',
    concept: 'Powers and exponent estimation',
    prompt: 'If 2^13 is approximately equal to 8000, then, of the following, which best approximates 2^26?',
    choices: ['640,000', '6,400,000', '64,000,000', '8000^13'],
    answer: 'c',
  },
  {
    id: 5,
    source: 'File 1',
    concept: 'Negative and fractional exponents',
    prompt: '2^-5 * 64^(2/3) =',
    choices: ['512', '1/512', '1', '1/2'],
    answer: 'd',
  },
  {
    id: 6,
    source: 'File 1',
    concept: 'Interpreting where a graph is negative',
    prompt: 'If f is a function whose graph is an upward-opening parabola crossing the x-axis at x = 1 and x = 3, then f(x) < 0 whenever:',
    choices: ['x < 1 or x > 3', 'x < 1', 'x > 3', '1 < x < 3'],
    answer: 'd',
  },
  {
    id: 7,
    source: 'File 1',
    concept: 'Solving logarithmic equations',
    prompt: 'If log_2(x - 6) = 6, then x =',
    choices: ['70', '64', '58', '6/log_2(6) + 6'],
    answer: 'a',
  },
  {
    id: 8,
    source: 'File 1',
    concept: 'Recognizing even-function symmetry',
    prompt: 'A function f is even if f(-x) = f(x) for each x in the domain of f. Of the following, which best represents the graph of an even function?',
    choices: ['A cubic-like curve without y-axis symmetry', 'A line with positive slope', 'A downward-opening parabola symmetric about the y-axis', 'A downward-opening parabola not symmetric about the y-axis'],
    answer: 'c',
  },
  {
    id: 9,
    source: 'File 1',
    concept: 'Zeros of a rational expression',
    prompt: 'If ((2x - 3)(x + 5))/(x - 7) = 0, then x =',
    choices: ['5, 7, -3/2', '5 or 3/2', '-5, 7, or 3/2', '-5 or 3/2'],
    answer: 'd',
  },
  {
    id: 10,
    source: 'File 1',
    concept: 'Identifying a circle from its equation',
    prompt: 'Of the following, which best represents the graph of x^2 + y^2 - 2y = 0?',
    choices: ['A circle tangent to the y-axis and centered to the right of the y-axis', 'A sideways-opening curve starting at the origin', 'A circle centered at (0, 1) with radius 1, tangent to the x-axis at the origin', 'An ellipse centered on the x-axis'],
    answer: 'c',
  },
  {
    id: 11,
    source: 'File 1',
    concept: 'Function evaluation with algebraic substitution',
    prompt: 'If f(x) = (5x + 3)/(2x + 3), then f(n + 1) =',
    choices: ['8/5', '(5n + 3)/(2n + 3) + 1', '(5n + 8)/(2n + 5)', '(5n + 4)/(2n + 4)'],
    answer: 'c',
  },
  {
    id: 12,
    source: 'File 1',
    concept: 'Slope between two points',
    prompt: 'The slope of the line that goes through the points (-5, 4) and (3, -12) is:',
    choices: ['-1/2', '8', '-2', '4'],
    answer: 'c',
  },
  {
    id: 13,
    source: 'File 1',
    concept: 'Solving quadratic equations',
    prompt: 'Find all solutions to the equation 3x^2 = 4x + 1.',
    choices: ['4/3, 1/3', '(2 + sqrt(7))/3, (2 - sqrt(7))/3', '(4 + 3sqrt(2))/6, (4 - 3sqrt(2))/6', '(2 + sqrt(2))/3, (2 - sqrt(2))/3'],
    answer: 'b',
  },
  {
    id: 14,
    source: 'File 1',
    concept: 'Interpreting slope in linear equations',
    prompt: 'In a standard coordinate system, the graph of the equation y = -3x + 7 is:',
    choices: ['a line falling to the right', 'a line rising to the right', 'a horizontal line', 'not a line'],
    answer: 'a',
  },
  {
    id: 15,
    source: 'File 1',
    concept: 'Absolute value inequalities',
    prompt: 'The inequality |x - 4| <= 8 is equivalent to:',
    choices: ['-4 <= x <= 12', '-12 <= x <= 4', '-12 <= x <= 12', 'x <= 12'],
    answer: 'a',
  },
  {
    id: 16,
    source: 'File 1',
    concept: 'Polynomial factor identities',
    prompt: 'The quantity a - b is a factor of how many of the following? I. a^2 - b^2 II. a^2 + b^2 III. a^3 - b^3 IV. a^3 + b^3',
    choices: ['one only', 'two only', 'three only', 'four'],
    answer: 'b',
  },
  {
    id: 17,
    source: 'File 1',
    concept: 'Distance formula / Pythagorean theorem',
    prompt: 'In the figure, the points are P(-2, 6), R(1, 6), and Q(1, 2). What is the distance between the points P and Q?',
    choices: ['11', '7', '6', '5'],
    answer: 'd',
  },
  {
    id: 18,
    source: 'File 1',
    concept: 'Rectangle word problem using area',
    prompt: 'The length of a certain rectangle is 6 meters more than twice its width. What is the perimeter of the rectangle if the area of the rectangle is 260 square meters?',
    choices: ['54 meters', '60 meters', '66 meters', '72 meters'],
    answer: 'd',
  },
  {
    id: 19,
    source: 'File 1',
    concept: 'Evaluating a function to find geometric area',
    prompt: 'A rectangle sits above the x-axis from x = 2 to x = 5, with its upper-left corner on the graph f(x) = x^3 - x + 7 at x = 2. What is the area of the rectangle? The figure is not drawn to scale.',
    choices: ['3', '27', '31', '39'],
    answer: 'd',
  },
  {
    id: 20,
    source: 'File 1',
    concept: 'Area scaling',
    prompt: 'A rectangle R has width x and length y. A rectangle S is formed from R by multiplying each side length of R by 4. What is the area of the portion of S lying outside R?',
    choices: ['16xy', '15xy', '4xy', 'x^4y^4'],
    answer: 'b',
  },
  {
    id: 21,
    source: 'File 1',
    concept: 'Degree-to-radian conversion',
    prompt: 'What is the radian measure of an angle whose degree measure is 240 degrees?',
    choices: ['pi/3', '2pi/3', '3pi/4', '4pi/3'],
    answer: 'd',
  },
  {
    id: 22,
    source: 'File 1',
    concept: 'Reciprocal trigonometric functions',
    prompt: 'csc(30 degrees) =',
    choices: ['2', 'sqrt(2)/3', 'sqrt(2)', 'sqrt(3)'],
    answer: 'a',
  },
  {
    id: 23,
    source: 'File 1',
    concept: 'Solving trigonometric equations on an interval',
    prompt: 'For which values of x in the interval 0 <= x <= 2pi does (sin x - 1)(sin x - 5) = 0?',
    choices: ['pi/2 only', '1 and 5', 'pi', '0 and 2pi'],
    answer: 'a',
  },
  {
    id: 24,
    source: 'File 1',
    concept: 'Right-triangle trigonometry using sine',
    prompt: 'In the figure, if sin R = 5/8 and r = 2, then what is q?',
    choices: ['16/5', '5/4', '5', '5/16'],
    answer: 'a',
  },
  {
    id: 25,
    source: 'File 2',
    concept: 'Basic trigonometric identities',
    prompt: 'If 0 degrees <= x < 90 degrees, then tan x cos x simplifies to:',
    choices: ['sin x', 'cos x', 'cot x', 'sec x', 'csc x'],
    answer: 'a',
  },
  {
    id: 26,
    source: 'File 2',
    concept: 'Laws of exponents with variables',
    prompt: 'The expression ((x^4 y^-3)^2)/(x^3 y^5) simplifies to:',
    choices: ['x^3/y^6', 'x^5/y^11', 'x^2/y^16', 'x^9 y^-6', 'None of these.'],
    answer: 'b',
  },
  {
    id: 27,
    source: 'File 2',
    concept: 'Exponential functions and exponent laws',
    prompt: 'If f(x) = 2^x, and a and b are any positive numbers, then f(a + b) is equivalent to:',
    choices: ['f(a) * f(b)', 'f(a)/f(b)', 'f(ab)', 'f(a) + f(b)', 'None of these.'],
    answer: 'a',
  },
  {
    id: 28,
    source: 'File 2',
    concept: 'Domain of a rational function',
    prompt: 'The domain of g(x) = 1/(3 - x) is:',
    choices: ['[3, infinity)', '(3, infinity)', '(-infinity, 3]', '(-infinity, 3)', 'None of these.'],
    answer: 'd',
  },
  {
    id: 29,
    source: 'File 2',
    concept: 'Solving linear equations with decimals',
    prompt: 'Solve for x: 6.4x - 3.2 = 4.4x + 1.2',
    choices: ['x = -2.2', 'x = 2', 'x = -1', 'x = 1.1', 'None of these.'],
    answer: 'e',
  },
  {
    id: 30,
    source: 'File 2',
    concept: 'Composition of functions',
    prompt: 'If f(x) = x^2 and g(x) = x^3 + 2x, what is the composition (f o g)(x)?',
    choices: ['x^5 + 2x^3', '(x^3 + 2x)^2', 'x^6 + 4x^2', '(x^3 + 2x)/x^4', 'None of these.'],
    answer: 'b',
  },
  {
    id: 31,
    source: 'File 2',
    concept: 'Domains of trigonometric functions',
    prompt: 'The function f(x) = cot x is not defined for:',
    choices: ['x = 0', 'x = pi/4', 'x = pi/2', 'x = pi/3', 'None of these.'],
    answer: 'a',
  },
  {
    id: 32,
    source: 'File 2',
    concept: 'Rational equations',
    prompt: 'One solution to the equation (x - 4)/(5x + 15) = 1/(x + 3) is:',
    choices: ['3', '1', '-3', '2sqrt(5) + 2', 'None of these.'],
    answer: 'e',
  },
  {
    id: 33,
    source: 'File 2',
    concept: 'Simplifying compound fractions',
    prompt: 'The expression ((1/b^2) + a^2)/((1/a^2) + b^2) simplifies to, ignoring the domain change when simplified:',
    choices: ['(1 + a^4)/(1 + b^4)', '(b^2 + a^2)/(a^2 b^2)', 'b^2/a^2', 'a^2/b^2', 'None of these.'],
    answer: 'd',
  },
  {
    id: 34,
    source: 'File 2',
    concept: 'Finding inverse functions',
    prompt: 'If f(x) = 5x - 2, the inverse function is:',
    choices: ['f^-1(x) = (1/5)x + 2', 'f^-1(x) = (x + 2)/5', 'f^-1(x) = (1/5)x - 1/2', 'f^-1(x) = 2x - 5', 'None of these.'],
    answer: 'b',
  },
  {
    id: 35,
    source: 'File 2',
    concept: 'Negative exponents and subtracting fractions',
    prompt: 'x^-3 - y^-3 is equivalent to:',
    choices: ['(x - y)^-3', '(x^3 y^3)/(x^3 - y^3)', '1/(x - y)^3', '(y^3 - x^3)/(x^3 y^3)', 'None of these.'],
    answer: 'd',
  },
  {
    id: 36,
    source: 'File 2',
    concept: 'Factoring using difference of cubes',
    prompt: 'The expression x^4y - xy^4 may be factored as:',
    choices: ['(x - y)(x^2 - y^2)(x^2 + y^2)', 'xy(x - y)^3', 'xy(x - y)(x^2 + xy + y^2)', '(x^2y - xy^2)^2', 'None of these.'],
    answer: 'c',
  },
  {
    id: 37,
    source: 'File 2',
    concept: 'Exact trigonometric values',
    prompt: 'The exact value of cos(4pi/3) is:',
    choices: ['sqrt(3)/2', '-sqrt(3)/2', '1/2', '-1/2', 'None of these.'],
    answer: 'd',
  },
  {
    id: 38,
    source: 'File 2',
    concept: 'Laws of logarithms',
    prompt: 'The expression log_2(2x) - 2log_2(y) + log_2(z) is equivalent to:',
    choices: ['log_2((2xz)/(y^2))', 'log_2((xz)/y)', 'log_2(2x - y^2 + z)', '(log_2(2x) log_2(z))/(2log_2(y))', 'None of these.'],
    answer: 'a',
  },
]

export const diagnosticAnswerNotes = [
  'Blue diagnostic set answers 1-24 are taken from the provided solution pages.',
  'Green diagnostic set answers 25-38 correspond to original source questions 1, 2, 3, 4, 6, 9, 11, 13, 14, 16, 17, 18, 19, and 20.',
  'Problem 28 uses g(x) = 1/sqrt(3 - x), so the domain is (-infinity, 3), answer d.',
  'Problem 32 solves to x = 9, which is not listed, so answer e.',
]

export const diagnosticSolutions = {
  1: ['32 years is four 8-year periods.', 'The money triples four times: $100 * 3^4 = 100 * 81 = 8,100$.'],
  2: ['Add $-x + 4y = -50$ and $x + y = 20$.', 'The $x$ terms cancel, giving $5y = -30$, so $y = -6$.'],
  3: ['Square base means base side $x$, base area $x^2$, top area $x^2$.', 'Height is $2x$, so four side faces each have area $2x^2$.', 'Total surface area is $2x^2 + 8x^2 = 10x^2$.'],
  4: ['Use exponent rules: $2^26 = (2^13)^2$.', 'Approximate with $8000^2 = 64,000,000$.'],
  5: ['$2^-5 = 1/32$.', '$64^(2/3) = (\\sqrt[3]{64})^2 = 4^2 = 16$.', 'Then $16/32 = 1/2$.'],
  6: ['An upward-opening parabola is below the $x$-axis between its two $x$-intercepts.', 'The intercepts are $x = 1$ and $x = 3$, so $f(x) < 0$ on $1 < x < 3$.'],
  7: ['Rewrite $log_2(x - 6) = 6$ as $2^6 = x - 6$.', '$64 = x - 6$, so $x = 70$.'],
  8: ['Even functions have y-axis symmetry.', 'A downward-opening parabola symmetric about the y-axis is even.'],
  9: ['A rational expression equals zero when its numerator equals zero.', 'Set $(2x - 3)(x + 5) = 0$.', 'Solutions are $x = 3/2$ and $x = -5$; $x = 7$ is excluded, not a zero.'],
  10: ['Complete the square: $x^2 + y^2 - 2y = 0$ becomes $x^2 + (y - 1)^2 = 1$.', 'The center is $(0,1)$, radius is $1$, tangent to the $x$-axis at the origin.'],
  11: ['Substitute $n + 1$ everywhere $x$ appears.', '$f(n+1) = [5(n+1)+3] / [2(n+1)+3] = (5n+8)/(2n+5)$.'],
  12: ['Slope $= (y_2 - y_1)/(x_2 - x_1)$.', '$(-12 - 4)/(3 - (-5)) = -16/8 = -2$.'],
  13: ['Set the equation to zero: $3x^2 - 4x - 1 = 0$.', 'Quadratic formula gives $x = [4 +- sqrt(16 + 12)]/6 = [4 +- sqrt(28)]/6 = (2 +- sqrt(7))/3$.'],
  14: ['The slope is $-3$.', 'Negative slope means the line falls as you move to the right.'],
  15: ['$|x - 4| <= 8$ means $x$ is within 8 units of 4.', 'So $-8 <= x - 4 <= 8$, giving $-4 <= x <= 12$.'],
  16: ['$a^2 - b^2$ has factor $a - b$.', '$a^2 + b^2$ does not factor over the reals.', '$a^3 - b^3$ has factor $a - b$.', '$a^3 + b^3$ has factor $a + b$, not $a - b$.', 'So two expressions have factor $a - b$.'],
  17: ['From $P(-2,6)$ to $Q(1,2)$, horizontal change is $3$ and vertical change is $-4$.', 'Distance is $sqrt(3^2 + 4^2) = 5$.'],
  18: ['Let width be $w$; length is $2w + 6$.', 'Area: $w(2w+6)=260$, so $2w^2+6w-260=0$, or $w^2+3w-130=0$.', 'Factor: $(w+13)(w-10)=0$, so $w=10$.', 'Length is $26$, perimeter is $2(10)+2(26)=72$.'],
  19: ['Width is $5 - 2 = 3$.', 'Height is $f(2)=2^3-2+7=13$.', 'Area is $3 * 13 = 39$.'],
  20: ['Original area is $xy$.', 'Scaling both side lengths by 4 makes new area $16xy$.', 'Outside portion is $16xy - xy = 15xy$.'],
  21: ['Convert degrees to radians by multiplying by $pi/180$.', '$240 * pi/180 = 4pi/3$.'],
  22: ['$csc$ is reciprocal of $sin$.', '$sin(30 degrees)=1/2$, so $csc(30 degrees)=2$.'],
  23: ['Set each factor equal to zero: $sin x = 1$ or $sin x = 5$.', '$sin x = 5$ is impossible.', 'On $0 <= x <= 2pi$, $sin x = 1$ only at $x = pi/2$.'],
  24: ['$sin R = opposite/hypotenuse = r/q$.', 'Given $sin R = 5/8$ and $r = 2$, solve $2/q = 5/8$.', '$5q = 16$, so $q = 16/5$.'],
  25: ['$tan x = sin x / cos x$.', '$tan x cos x = (sin x / cos x)cos x = sin x$.'],
  26: ['Square the numerator: $(x^4 y^-3)^2 = x^8 y^-6$.', 'Divide by $x^3 y^5$ by subtracting exponents: $x^(8-3)y^(-6-5)=x^5y^-11=x^5/y^11$.'],
  27: ['$f(a+b)=2^(a+b)$.', 'Exponent law gives $2^(a+b)=2^a * 2^b = f(a)f(b)$.'],
  28: ['The denominator/radical expression requires $3 - x > 0$.', 'So $x < 3$, giving $(-infinity, 3)$.'],
  29: ['Subtract $4.4x$ from both sides: $2x - 3.2 = 1.2$.', 'Add $3.2$: $2x = 4.4$.', '$x = 2.2$, which is not listed, so choose None of these.'],
  30: ['Composition means $f(g(x))$.', 'Since $f(x)=x^2$, $f(g(x)) = (x^3 + 2x)^2$.'],
  31: ['$cot x = cos x / sin x$.', 'It is undefined when $sin x = 0$.', 'Among the choices, $x = 0$ makes $sin x = 0$.'],
  32: ['Because $5x+15 = 5(x+3)$, the equation becomes $(x-4)/(5(x+3)) = 1/(x+3)$.', 'For $x$ not equal to $-3$, multiply by $x+3$: $(x-4)/5 = 1$.', '$x - 4 = 5$, so $x = 9$, which is not listed.'],
  33: ['Rewrite numerator as $(1 + a^2b^2)/b^2$.', 'Rewrite denominator as $(1 + a^2b^2)/a^2$.', 'Divide to get $a^2/b^2$ after canceling the common factor.'],
  34: ['Start $y = 5x - 2$.', 'Swap $x$ and $y$: $x = 5y - 2$.', 'Solve for $y$: $x + 2 = 5y$, so $y = (x + 2)/5$.'],
  35: ['Rewrite negative exponents: $x^-3 - y^-3 = 1/x^3 - 1/y^3$.', 'Common denominator $x^3y^3$ gives $(y^3 - x^3)/(x^3y^3)$.'],
  36: ['Factor out $xy$: $x^4y - xy^4 = xy(x^3 - y^3)$.', 'Use difference of cubes: $x^3 - y^3 = (x-y)(x^2 + xy + y^2)$.'],
  37: ['$4pi/3$ is in Quadrant III with reference angle $pi/3$.', 'Cosine is negative in Quadrant III and $cos(pi/3)=1/2$.', 'So $cos(4pi/3) = -1/2$.'],
  38: ['Use log rules: $log_2(2x)+log_2(z)=log_2(2xz)$.', 'Use power rule: $2log_2(y)=log_2(y^2)$.', 'Subtract logs: $log_2(2xz)-log_2(y^2)=log_2((2xz)/(y^2))$.'],
}
